### ISSUE TITLE
Ionic / ngCordova git clone failing

### ISSUE THREAD

**Issue by jayrmotta** [IonicBrazil/ionic-garden#40]
Hi there.. I'm trying to install the project to test and contribute but the install fail when it tries to find some folders that should be there after a `git clone` of both Ionic and ngCordova:

```javascript
> ionic-garden@1.0.0 postinstall /Users/jayrmotta/Development/sandbox/ionic-garden
> bower install && gulp install-source-modules

[20:59:20] Using gulpfile ~/Development/sandbox/ionic-garden/gulpfile.js
[20:59:20] Starting 'install-source-modules'...
git clone git://github.com/driftyco/ionic.git modules/ionic
[20:59:20] 'install-source-modules' errored after 379 μs
[20:59:20] Error: ENOENT, no such file or directory '/Users/jayrmotta/Development/sandbox/ionic-garden/modules/ionic'
    at Object.fs.lstatSync (fs.js:691:18)
    at /Users/jayrmotta/Development/sandbox/ionic-garden/gulp/tasks/install-source-modules.js:21:24
    at Array.forEach (native)
    at Gulp.<anonymous> (/Users/jayrmotta/Development/sandbox/ionic-garden/gulp/tasks/install-source-modules.js:12:9)
    at module.exports (/Users/jayrmotta/Development/sandbox/ionic-garden/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jayrmotta/Development/sandbox/ionic-garden/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jayrmotta/Development/sandbox/ionic-garden/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jayrmotta/Development/sandbox/ionic-garden/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/jayrmotta/Development/sandbox/ionic-garden/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
```

Is anyone else able to reproduce the same problem?

**Comment by giorgiofellipe** [comment]
Thank you @jayrmotta for reporting this, it's fixed now!

**Comment by jayrmotta** [comment]
Amazing @giorgiofellipe, I was looking into that trying to understand because this `Error: ENOENT, no such file or directory` seems to be common in the community.

Anyway, thank you so much!!
